const test_SECONDARY_ACCENT_COLOR = "palette.primary.main"
const COLOR_BITCOIN_GOLD = "rgb(234, 151,61)"
const COLOR_ZCASH_GOLD = "#FFD700"
const COLOR_USDC_BLUE = "rgb(58, 113, 190)"

export { test_SECONDARY_ACCENT_COLOR, COLOR_BITCOIN_GOLD, COLOR_USDC_BLUE, COLOR_ZCASH_GOLD }